### ISSUE TITLE
Zooming on nodes - 'view reset' button?

### ISSUE THREAD

**Issue by lionspaws** [AU-ExoMars/PCOT#47]
*Might be a Mac issue, but not necessarily*

While trying to move around the nodes view I accidentally zoomed out really far, now I can't see anything anymore so I'm not even sure if I'm zooming in on a blank area or if I'm not zooming at all. 

Temporary workaround - saving and reloading PCOT does reset the view, however reloading the file without quitting PCOT doesn't.

**Comment by jimfinnis** [comment]
Oh yes, definitely need this. Not sure where to put it, mind.

**Comment by lionspaws** [comment]
Could it be something in the right-click menu on the node area? “Reset view” that just sets the zoom/centre location back to wherever it stated would be awesome, just to reorient yourself.

**Comment by jimfinnis** [comment]
Heh - context menus are easy and the view probably needs one, and the fit turns out to be a one-liner.
