### ISSUE TITLE
Application menu stops working

### ISSUE THREAD

**Issue by lionspaws** [AU-ExoMars/PCOT#48]
When using PCOT on Mac the application menu will sometimes not do anything until I give focus to another application then switch back and it works fine. I've not worked out if there's a pattern to it yet, will update when I do...

**Comment by lionspaws** [comment]
On further playing around it seems to be happening when PCOT first starts up, and it's happening every time very consistently.

**Comment by jimfinnis** [comment]
Can you provide exact repro steps for the next time I'm on a Mac?

**Comment by lionspaws** [comment]
(1) Run PCOT from terminal (screenshot below in case it contains anything useful)
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/11976517/201728071-9f9d1bad-4b95-4689-8a83-125dc2d57c92.png">

(2) immediately go to click on menu bar:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/11976517/201727870-e6fa854b-ae13-44b6-8bf9-ec05e7b412bf.png">
None of the items visible in the screenshot do anything, even the Apple. Items on the right hand side of the menu work fine. 

(3) Click anywhere away from PCOT, click back, menu options now work fine.

**Comment by jimfinnis** [comment]
https://bugreports.qt.io/browse/QTBUG-48829

"Not a bug. That's just how OS X is."

I think we'll have to leave this one, it's apparently the expected behaviour for opening apps from the command line - they never get the focus until you click away and come back.
