### ISSUE TITLE
Node deletion

### ISSUE THREAD

**Issue by lionspaws** [AU-ExoMars/PCOT#50]
I can't delete nodes on my laptop because I haven't got a DEL key, only a backspace!

**Comment by lionspaws** [comment]
There's not really a standard, but backspace is quite commonly used like this. For text editing I can use fn+backspace but I use it so irregularly that I tend to work around it by moving with arrows/shift-selecting..!

**Comment by jimfinnis** [comment]
Fixed, hopefully - and easily. Can't test at the moment.
