### ISSUE TITLE
Window auto-resizing

### ISSUE THREAD

**Issue by lionspaws** [AU-ExoMars/PCOT#51]
(Might be a Mac thing?)

When I open the tab for the PCT fitting node the window auto-resizes to try to fit everything in, but it doesn't all fit on screen so I lose a slice off the bottom of the PCOT window:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11976517/201725763-267f694f-5146-4359-89bb-b2d8e9772b37.png">

Going fullscreen rearranges it a bit more tidily but chops sections from the bottom:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11976517/201726156-431be1c9-593b-44a0-9d9e-f0787169da52.png">

 I can get to the comments bit by dragging from the dot at the base, but I don't think I'm getting all of it?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11976517/201726251-f467c959-b312-494a-a363-bca686c79f12.png">

I wonder if bit of tweaking could improve this behaviour, if so that would be awesome, but it's not urgent.

Note - slightly random nodes in use as I'm trying to understand how your awesome PCT fitting works so I can do something similar for the RIM.

**Comment by jimfinnis** [comment]
Not sure about this one. I'll need to run on a lower res system to see what happens, but at the end of the day I think we're going to have to mandate a minimum screen size!

**Comment by jimfinnis** [comment]
I actually see this on PC too on the laptop! It's matplotlib - if the widget holding the plot is too small, it just makes it bigger. At the moment that plot is a dummy - I've changed its aspect ratio and that should fix it (should be in the dev branch).

**Comment by jimfinnis** [comment]
Accidental close :)
